from io import StringIO

import pytest

import XpongeCPP as Xponge


def test_load_gro_reads_triclinic_box_and_updates_molecule():
    mol = Xponge.load_pdb(
        StringIO(
            """\
ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       1.000   0.000   0.000  1.00  0.00           C
TER
END
"""
        ),
        unterminal_residues=[1],
        ignore_unknown_name=True,
    )
    gro = StringIO(
        """\
Generated by test
2
    1ALA      N    1   0.100   0.200   0.300
    1ALA     CA    2   0.400   0.500   0.600
   1.00000   2.00000   3.00000   0.00000   0.00000   0.50000   0.00000   0.20000   0.30000
"""
    )

    crd, box = Xponge.load_gro(gro, mol)

    assert [value for row in crd for value in row] == pytest.approx([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
    assert mol.box_length == pytest.approx(box[:3])
    assert mol.box_angle == pytest.approx(box[3:])
    assert mol.residues[0].atoms[0].x == pytest.approx(1.0)
    assert box[0] == pytest.approx(10.0)
    assert box[1] == pytest.approx((20.0**2 + 5.0**2) ** 0.5)
    assert box[2] == pytest.approx((30.0**2 + 2.0**2 + 3.0**2) ** 0.5)
    assert box[3] != pytest.approx(90.0)
    assert box[4] != pytest.approx(90.0)
    assert box[5] != pytest.approx(90.0)


def test_save_gro_writes_box_angle_roundtrip(tmp_path):
    mol = Xponge.load_pdb(
        StringIO(
            """\
ATOM      1  N   ALA A   1       1.000   2.000   3.000  1.00  0.00           N
ATOM      2  CA  ALA A   1       4.000   5.000   6.000  1.00  0.00           C
TER
END
"""
        ),
        unterminal_residues=[1],
        ignore_unknown_name=True,
    )
    mol.box_length = [10.0, 20.6155281281, 30.2158898595]
    mol.box_angle = [78.4510609362, 86.2076748623, 75.9637565321]
    out = tmp_path / "case.gro"

    Xponge.save_gro(mol, str(out))
    _, box = Xponge.load_gro(str(out))

    assert box[:3] == pytest.approx(mol.box_length, abs=2e-3)
    assert box[3:] == pytest.approx(mol.box_angle, abs=2e-3)


def test_load_gro_uses_fixed_coordinate_columns_and_ignores_velocities():
    gro = StringIO(
        """\
Generated by test
1
    1ALA     CA    1   0.100   0.200   0.300  9.9999  8.8888  7.7777
   1.00000   1.00000   1.00000
"""
    )

    crd, box = Xponge.load_gro(gro)

    assert crd == [[1.0, 2.0, 3.0]]
    assert box == [10.0, 10.0, 10.0, 90.0, 90.0, 90.0]


def test_load_gro_read_box_angle_false_applies_without_molecule():
    gro = StringIO(
        """\
Generated by test
1
    1ALA      CA    1   0.100   0.200   0.300
   1.00000   2.00000   3.00000   0.00000   0.00000   0.50000   0.00000   0.20000   0.30000
"""
    )

    _, box = Xponge.load_gro(gro, read_box_angle=False)

    assert box[:3] == pytest.approx([10.0, (20.0**2 + 5.0**2) ** 0.5, (30.0**2 + 2.0**2 + 3.0**2) ** 0.5])
    assert box[3:] == [90.0, 90.0, 90.0]


def test_save_gro_without_explicit_box_matches_xponge_padding(tmp_path):
    mol = Xponge.load_pdb(
        StringIO(
            """\
ATOM      1  N   ALA A   1      -1.000   2.000   0.500  1.00  0.00           N
ATOM      2  CA  ALA A   1       3.000   5.000   4.500  1.00  0.00           C
TER
END
"""
        ),
        unterminal_residues=[1],
        ignore_unknown_name=True,
    )
    out = tmp_path / "padding.gro"

    Xponge.save_gro(mol, str(out))
    crd, box = Xponge.load_gro(str(out))

    assert [value for row in crd for value in row] == pytest.approx([3.0, 3.0, 3.0, 7.0, 6.0, 7.0])
    assert box == pytest.approx([10.0, 9.0, 10.0, 90.0, 90.0, 90.0])
