"""Provider-neutral scientific manifests for SPONGE input cases.

The manifest intentionally describes parsed scientific state instead of file
bytes.  It is therefore suitable for comparing SPONGE input generated by
Xponge-origin and XpongeCPP even when harmless formatting differs.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

from ._core import load_coordinate
from .io_bundle import convert_bundle_to_legacy, scan_legacy_case
from .io_bundle.contracts import contracts_by_legacy_key
from .io_bundle.legacy_case import LegacyCase
from .io_bundle.topology_parsers import parse_topology_file


SCHEMA = "xponge.scientific_manifest"
SCHEMA_VERSION = 1

_TEXT_KEYS = {
    "atom_name_in_file": "/atoms/name",
    "atom_type_name_in_file": "/atoms/type_name",
    "resname_in_file": "/residues/name",
}


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_array(value: np.ndarray) -> dict[str, Any]:
    array = np.asarray(value)
    return {
        "dtype": str(array.dtype),
        "shape": list(array.shape),
        "values": array.tolist(),
    }


def _read_counted_text(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return []
    try:
        count = int(lines[0].strip())
    except ValueError:
        return lines
    values = lines[1:]
    if len(values) != count:
        raise ValueError(
            f"{path} declares {count} text records but contains {len(values)}"
        )
    return values


def _find_mdin(root: Path, mdin: str | Path | None) -> Path | None:
    if mdin is not None:
        path = Path(mdin)
        if not path.is_absolute():
            path = root / path
        if not path.is_file():
            raise FileNotFoundError(f"SPONGE mdin does not exist: {path}")
        return path
    candidates = sorted(root.glob("mdin*.toml"))
    if not candidates:
        return None
    if len(candidates) != 1:
        raise ValueError(
            f"expected one mdin*.toml in {root}, found {len(candidates)}"
        )
    return candidates[0]


def _materialize_raw_case(
    root: Path,
    *,
    mdin: str | Path | None,
    temporary_root: Path | None,
) -> tuple[Path, Path | None]:
    topology_h5 = root / "topology.spgp.h5"
    if not topology_h5.is_file():
        return root, _find_mdin(root, mdin)
    if temporary_root is None:
        raise ValueError(
            "temporary_root is required when building a manifest from a bundle"
        )
    prefix = str(root.name or "system")
    converted = temporary_root / "legacy"
    result = convert_bundle_to_legacy(root, converted, prefix=prefix)
    return converted, Path(result.generated_mdin)


def _set_string_dataset(
    datasets: dict[str, dict[str, Any]],
    path: str,
    values: list[str],
) -> None:
    datasets[path] = {
        "dtype": "string",
        "shape": [len(values)],
        "values": values,
    }


def _canonicalize_interactions(
    datasets: dict[str, dict[str, Any]],
    atom_map: np.ndarray,
    *,
    stem: str,
    atom_arity: int,
    parameter_names: tuple[str, ...],
    reversible: bool,
) -> None:
    atom_path = f"/forcefield/{stem}/atoms"
    if atom_path not in datasets:
        return
    parameter_paths = tuple(
        f"/forcefield/{stem}/{name}" for name in parameter_names
    )
    if any(path not in datasets for path in parameter_paths):
        return
    atoms = np.asarray(datasets[atom_path]["values"], dtype=np.int64)
    if atoms.ndim != 2 or atoms.shape[1] != atom_arity:
        return
    mapped_atoms = atom_map[atoms]
    parameters = [
        np.asarray(datasets[path]["values"]) for path in parameter_paths
    ]
    records: list[tuple[Any, ...]] = []
    for index, raw_atoms in enumerate(mapped_atoms):
        atom_tuple = tuple(int(value) for value in raw_atoms)
        if reversible:
            atom_tuple = min(atom_tuple, atom_tuple[::-1])
        records.append((
            atom_tuple,
            *(parameter[index].tolist() for parameter in parameters),
        ))
    order = sorted(range(len(records)), key=records.__getitem__)
    datasets[atom_path] = _json_array(np.asarray(
        [records[index][0] for index in order],
        dtype=np.int32,
    ))
    for offset, path in enumerate(parameter_paths, start=1):
        datasets[path] = _json_array(np.asarray([
            records[index][offset] for index in order
        ]))


def _canonicalize_lj_types(
    datasets: dict[str, dict[str, Any]],
    atom_order: np.ndarray,
) -> None:
    type_path = "/forcefield/lj/type"
    count_path = "/forcefield/lj/atom_type_count"
    atom_type_path = "/atoms/type_name"
    pair_a_path = "/forcefield/lj/pair_A_12"
    pair_b_path = "/forcefield/lj/pair_B_6"
    required = (
        type_path,
        count_path,
        atom_type_path,
        pair_a_path,
        pair_b_path,
    )
    if any(path not in datasets for path in required):
        return
    raw_ids = np.asarray(datasets[type_path]["values"], dtype=np.int64)
    atom_type_names = list(datasets[atom_type_path]["values"])
    type_count = int(np.asarray(
        datasets[count_path]["values"],
    ).reshape(()))
    if (
        raw_ids.shape != (len(atom_type_names),)
        or type_count <= 0
        or np.any(raw_ids < 0)
        or np.any(raw_ids >= type_count)
    ):
        return
    labels: list[tuple[str, ...]] = []
    for type_id in range(type_count):
        names = sorted({
            str(atom_type_names[index])
            for index in np.flatnonzero(raw_ids == type_id)
        })
        labels.append(tuple(names) if names else (f"<unused:{type_id}>",))
    canonical_old_ids = sorted(range(type_count), key=labels.__getitem__)
    old_to_new = np.empty(type_count, dtype=np.int32)
    for new_id, old_id in enumerate(canonical_old_ids):
        old_to_new[old_id] = new_id
    datasets[type_path] = _json_array(old_to_new[raw_ids[atom_order]])

    def reorder_pairs(path: str) -> None:
        flat = np.asarray(datasets[path]["values"])
        if flat.size != type_count * (type_count + 1) // 2:
            return
        matrix = np.zeros((type_count, type_count), dtype=flat.dtype)
        cursor = 0
        for first in range(type_count):
            for second in range(first + 1):
                matrix[first, second] = flat[cursor]
                matrix[second, first] = flat[cursor]
                cursor += 1
        reordered: list[Any] = []
        for first in canonical_old_ids:
            first_new = int(old_to_new[first])
            for second_new in range(first_new + 1):
                second = canonical_old_ids[second_new]
                reordered.append(matrix[first, second])
        datasets[path] = _json_array(np.asarray(reordered, dtype=flat.dtype))

    reorder_pairs(pair_a_path)
    reorder_pairs(pair_b_path)


def _canonicalize_exclusions(
    datasets: dict[str, dict[str, Any]],
    atom_order: np.ndarray,
    atom_map: np.ndarray,
) -> None:
    offset_path = "/topology/exclusions/offset"
    list_path = "/topology/exclusions/list"
    if offset_path not in datasets or list_path not in datasets:
        return
    offsets = np.asarray(datasets[offset_path]["values"], dtype=np.int64)
    excluded = np.asarray(datasets[list_path]["values"], dtype=np.int64)
    if offsets.shape != (len(atom_order) + 1,):
        return
    pairs: set[tuple[int, int]] = set()
    for old_atom in range(len(atom_order)):
        mapped_atom = int(atom_map[old_atom])
        values = atom_map[excluded[offsets[old_atom]:offsets[old_atom + 1]]]
        for mapped_excluded in values:
            pair = tuple(sorted((mapped_atom, int(mapped_excluded))))
            if pair[0] != pair[1]:
                pairs.add(pair)
    del datasets[offset_path]
    del datasets[list_path]
    datasets["/topology/exclusions/pairs"] = _json_array(
        np.asarray(sorted(pairs), dtype=np.int32).reshape(-1, 2)
    )


def _canonicalize_atom_order(
    datasets: dict[str, dict[str, Any]],
) -> None:
    """Make atom-indexed state independent of provider insertion order."""

    name_path = "/atoms/name"
    residue_path = "/atoms/residue_index"
    if name_path not in datasets or residue_path not in datasets:
        return
    names = [str(value) for value in datasets[name_path]["values"]]
    residue_indices = np.asarray(
        datasets[residue_path]["values"],
        dtype=np.int64,
    )
    if residue_indices.shape != (len(names),):
        return
    keys = [
        (int(residue_indices[index]), names[index])
        for index in range(len(names))
    ]
    if len(set(keys)) != len(keys):
        return
    atom_order = np.asarray(sorted(
        range(len(keys)),
        key=keys.__getitem__,
    ), dtype=np.int64)
    atom_map = np.empty(len(atom_order), dtype=np.int32)
    atom_map[atom_order] = np.arange(len(atom_order), dtype=np.int32)

    atom_paths = (
        "/atoms/charge",
        "/atoms/mass",
        "/atoms/residue_index",
        "/atoms/type_name",
        "/restart/position",
    )
    _canonicalize_lj_types(datasets, atom_order)
    for path in atom_paths:
        if path not in datasets:
            continue
        if path == "/atoms/type_name":
            values = [str(value) for value in datasets[path]["values"]]
            _set_string_dataset(
                datasets,
                path,
                [values[index] for index in atom_order],
            )
            continue
        values = np.asarray(datasets[path]["values"])
        if values.shape and values.shape[0] == len(atom_order):
            datasets[path] = _json_array(values[atom_order])
    _set_string_dataset(
        datasets,
        name_path,
        [names[index] for index in atom_order],
    )

    _canonicalize_interactions(
        datasets,
        atom_map,
        stem="bond",
        atom_arity=2,
        parameter_names=("k", "r0"),
        reversible=True,
    )
    _canonicalize_interactions(
        datasets,
        atom_map,
        stem="angle",
        atom_arity=3,
        parameter_names=("k", "theta0"),
        reversible=True,
    )
    _canonicalize_interactions(
        datasets,
        atom_map,
        stem="nb14",
        atom_arity=2,
        parameter_names=("params",),
        reversible=True,
    )
    dihedral_path = "/forcefield/dihedral/atoms"
    if dihedral_path in datasets:
        atoms = np.asarray(
            datasets[dihedral_path]["values"],
            dtype=np.int64,
        )
        datasets[dihedral_path] = _json_array(atom_map[atoms])
    _canonicalize_exclusions(datasets, atom_order, atom_map)


def _canonicalize_dihedrals(
    datasets: dict[str, dict[str, Any]],
) -> None:
    atom_path = "/forcefield/dihedral/atoms"
    if atom_path not in datasets:
        return
    parameter_paths = (
        "/forcefield/dihedral/periodicity",
        "/forcefield/dihedral/k",
        "/forcefield/dihedral/phi0",
    )
    if any(path not in datasets for path in parameter_paths):
        return
    bond_atoms = np.asarray(
        datasets.get("/forcefield/bond/atoms", {}).get("values", []),
        dtype=np.int64,
    )
    bond_pairs = {
        frozenset((int(atom1), int(atom2))) for atom1, atom2 in bond_atoms
    }
    atoms = np.asarray(datasets[atom_path]["values"], dtype=np.int64)
    parameters = [
        np.asarray(datasets[path]["values"]) for path in parameter_paths
    ]
    records = []
    kinds = []
    for index, raw_atoms in enumerate(atoms):
        atom_tuple = tuple(int(value) for value in raw_atoms)
        centers = [
            atom
            for atom in atom_tuple
            if all(
                other == atom or frozenset((atom, other)) in bond_pairs
                for other in atom_tuple
            )
        ]
        if len(centers) == 1:
            center = centers[0]
            outer = sorted(atom for atom in atom_tuple if atom != center)
            canonical_atoms = (outer[0], outer[1], center, outer[2])
            kind = "improper"
        else:
            reverse = atom_tuple[::-1]
            canonical_atoms = min(atom_tuple, reverse)
            kind = "proper"
        record = (
            canonical_atoms,
            *(parameter[index].item() for parameter in parameters),
        )
        records.append(record)
        kinds.append(kind)
    order = sorted(range(len(records)), key=records.__getitem__)
    datasets[atom_path] = _json_array(
        np.asarray([records[index][0] for index in order], dtype=np.int32)
    )
    for offset, path in enumerate(parameter_paths, start=1):
        datasets[path] = _json_array(
            np.asarray([records[index][offset] for index in order])
        )
    ordered_kinds = [kinds[index] for index in order]
    datasets["/forcefield/dihedral/kind"] = {
        "dtype": "string",
        "shape": [len(ordered_kinds)],
        "values": ordered_kinds,
    }


def _canonicalize_cmaps(
    datasets: dict[str, dict[str, Any]],
) -> None:
    """Canonicalize CMAP tables independently of provider type numbering.

    SPONGE CMAP type identifiers are local indices into the grids written in
    ``system_cmap.txt``.  Xponge-origin numbers them by first topology use,
    whereas XpongeCPP retains force-field declaration order.  Moreover,
    multiple chemical CMAP types can share an identical numerical grid.  The
    numerical grid is the complete scientific identity available in SPONGE
    input, so manifests deduplicate and sort by that identity before remapping
    interaction records.
    """

    atom_path = "/forcefield/cmap/atoms"
    type_path = "/forcefield/cmap/type"
    resolution_path = "/forcefield/cmap/resolution"
    grid_path = "/forcefield/cmap/grid_value"
    required = (atom_path, type_path, resolution_path, grid_path)
    if any(path not in datasets for path in required):
        return

    atoms = np.asarray(datasets[atom_path]["values"], dtype=np.int64)
    raw_types = np.asarray(datasets[type_path]["values"], dtype=np.int64)
    resolutions = np.asarray(
        datasets[resolution_path]["values"], dtype=np.int64
    )
    grid_values = np.asarray(datasets[grid_path]["values"])
    if (
        atoms.ndim != 2
        or atoms.shape[1] != 5
        or raw_types.shape != (atoms.shape[0],)
        or np.any(resolutions <= 0)
        or np.any(raw_types < 0)
        or np.any(raw_types >= len(resolutions))
    ):
        return

    signatures: list[tuple[int, tuple[Any, ...]]] = []
    cursor = 0
    for resolution in resolutions:
        size = int(resolution) ** 2
        block = grid_values[cursor:cursor + size]
        if block.size != size:
            return
        signatures.append((
            int(resolution),
            tuple(block.tolist()),
        ))
        cursor += size
    if cursor != grid_values.size:
        return

    canonical_signatures = sorted(set(signatures))
    signature_to_type = {
        signature: index
        for index, signature in enumerate(canonical_signatures)
    }
    remapped_types = np.asarray(
        [signature_to_type[signatures[int(type_id)]] for type_id in raw_types],
        dtype=np.int32,
    )
    records = [
        (tuple(int(value) for value in atoms[index]), int(remapped_types[index]))
        for index in range(len(atoms))
    ]
    order = sorted(range(len(records)), key=records.__getitem__)
    datasets[atom_path] = _json_array(np.asarray(
        [records[index][0] for index in order], dtype=np.int32
    ))
    datasets[type_path] = _json_array(np.asarray(
        [records[index][1] for index in order], dtype=np.int32
    ))
    datasets[resolution_path] = _json_array(np.asarray(
        [signature[0] for signature in canonical_signatures], dtype=np.int32
    ))
    canonical_grid = [
        value
        for _, values in canonical_signatures
        for value in values
    ]
    datasets[grid_path] = _json_array(np.asarray(
        canonical_grid, dtype=grid_values.dtype
    ))


def _scan_case(root: Path, mdin_path: Path | None) -> LegacyCase:
    if mdin_path is not None:
        return scan_legacy_case(root, mdin_path)
    coordinate_files = sorted(root.glob("*_coordinate.txt"))
    if len(coordinate_files) != 1:
        raise ValueError(
            f"cannot infer SPONGE prefix in {root}: expected one "
            f"*_coordinate.txt, found {len(coordinate_files)}"
        )
    coordinate_suffix = "_coordinate.txt"
    prefix = str(coordinate_files[0])[: -len(coordinate_suffix)]
    return LegacyCase(
        root=root,
        mdin_path=root / "<inferred>",
        mdin_text="",
        commands={"default_in_file_prefix": prefix},
    )


def build_scientific_manifest(
    case_root: str | Path,
    *,
    mdin: str | Path | None = None,
    case_id: str | None = None,
    metadata: dict[str, Any] | None = None,
    temporary_root: str | Path | None = None,
) -> dict[str, Any]:
    """Parse a raw or bundled SPONGE input case into a stable JSON manifest."""

    root = Path(case_root).resolve()
    temporary = (
        Path(temporary_root).resolve() if temporary_root is not None else None
    )
    raw_root, mdin_path = _materialize_raw_case(
        root,
        mdin=mdin,
        temporary_root=temporary,
    )
    case = _scan_case(raw_root, mdin_path)
    datasets: dict[str, dict[str, Any]] = {}
    files: dict[str, dict[str, Any]] = {}

    coordinate_path = case.resolve_legacy_input_path("coordinate_in_file")
    if coordinate_path is not None and coordinate_path.is_file():
        coordinate, box = load_coordinate(str(coordinate_path))
        datasets["/restart/position"] = _json_array(
            np.asarray(coordinate, dtype=np.float64)
        )
        datasets["/restart/box"] = _json_array(
            np.asarray(box, dtype=np.float64)
        )

    input_keys = {
        key for key in case.commands if key.endswith("_in_file")
    } | {
        key for key in contracts_by_legacy_key() if key.endswith("_in_file")
    } | set(_TEXT_KEYS)
    for key in sorted(input_keys):
        if not key.endswith("_in_file"):
            continue
        path = case.resolve_legacy_input_path(key)
        if path is None or not path.is_file():
            continue
        files[key] = {
            "name": path.name,
            "sha256": _sha256(path),
            "size": path.stat().st_size,
        }
        text_path = _TEXT_KEYS.get(key)
        if text_path is not None:
            values = _read_counted_text(path)
            datasets[text_path] = {
                "dtype": "string",
                "shape": [len(values)],
                "values": values,
            }
            continue
        parsed = parse_topology_file(key, path)
        if parsed is None:
            continue
        for dataset in parsed:
            if dataset.path in datasets:
                raise ValueError(f"duplicate scientific dataset: {dataset.path}")
            datasets[dataset.path] = _json_array(dataset.data)

    _canonicalize_atom_order(datasets)
    _canonicalize_dihedrals(datasets)
    _canonicalize_cmaps(datasets)
    return {
        "schema": SCHEMA,
        "schema_version": SCHEMA_VERSION,
        "case_id": case_id or root.name,
        "metadata": dict(metadata or {}),
        "source": {
            "root": str(root),
            "mdin": mdin_path.name if mdin_path is not None else None,
            "mdin_sha256": _sha256(mdin_path) if mdin_path is not None else None,
        },
        "datasets": dict(sorted(datasets.items())),
        "files": files,
    }


def _tolerance(path: str) -> tuple[float, float]:
    if path == "/restart/position" or path == "/restart/box":
        return 0.0, 1.0e-6
    if path == "/atoms/charge":
        return 0.0, 1.0e-8
    return 1.0e-10, 1.0e-12


def compare_scientific_manifests(
    reference: dict[str, Any],
    candidate: dict[str, Any],
) -> dict[str, Any]:
    """Return a compact, machine-readable semantic diff."""

    issues: list[dict[str, Any]] = []
    if reference.get("schema") != SCHEMA or candidate.get("schema") != SCHEMA:
        issues.append({"kind": "schema_mismatch"})
    if reference.get("schema_version") != candidate.get("schema_version"):
        issues.append({
            "kind": "schema_version_mismatch",
            "reference": reference.get("schema_version"),
            "candidate": candidate.get("schema_version"),
        })

    reference_datasets = reference.get("datasets") or {}
    candidate_datasets = candidate.get("datasets") or {}
    reference_keys = set(reference_datasets)
    candidate_keys = set(candidate_datasets)
    if reference_keys != candidate_keys:
        issues.append({
            "kind": "dataset_set_mismatch",
            "missing": sorted(reference_keys - candidate_keys),
            "unexpected": sorted(candidate_keys - reference_keys),
        })

    compared = 0
    for path in sorted(reference_keys & candidate_keys):
        expected = reference_datasets[path]
        actual = candidate_datasets[path]
        if expected.get("shape") != actual.get("shape"):
            issues.append({
                "kind": "shape_mismatch",
                "path": path,
                "reference": expected.get("shape"),
                "candidate": actual.get("shape"),
            })
            continue
        expected_dtype = str(expected.get("dtype"))
        actual_dtype = str(actual.get("dtype"))
        if expected_dtype == "string" or actual_dtype == "string":
            if expected_dtype != actual_dtype or expected.get("values") != actual.get("values"):
                issues.append({"kind": "exact_value_mismatch", "path": path})
            compared += 1
            continue
        expected_values = np.asarray(expected.get("values"))
        actual_values = np.asarray(actual.get("values"))
        if expected_values.dtype.kind in "iu" or actual_values.dtype.kind in "iu":
            if not np.array_equal(expected_values, actual_values):
                mismatch = np.flatnonzero(
                    expected_values.reshape(-1) != actual_values.reshape(-1)
                )
                issues.append({
                    "kind": "exact_value_mismatch",
                    "path": path,
                    "first_index": int(mismatch[0]) if mismatch.size else None,
                    "count": int(mismatch.size),
                })
        else:
            rtol, atol = _tolerance(path)
            delta = np.abs(
                expected_values.astype(np.float64)
                - actual_values.astype(np.float64)
            )
            allowed = atol + rtol * np.abs(expected_values.astype(np.float64))
            failed = delta > allowed
            if np.any(failed):
                flat_delta = delta.reshape(-1)
                issues.append({
                    "kind": "numeric_mismatch",
                    "path": path,
                    "rtol": rtol,
                    "atol": atol,
                    "count": int(np.count_nonzero(failed)),
                    "max_abs": float(np.max(flat_delta)),
                    "rms": float(np.sqrt(np.mean(flat_delta * flat_delta))),
                    "first_index": int(np.flatnonzero(failed.reshape(-1))[0]),
                })
        compared += 1

    return {
        "schema": "xponge.scientific_manifest.diff",
        "schema_version": 1,
        "ok": not issues,
        "reference_case_id": reference.get("case_id"),
        "candidate_case_id": candidate.get("case_id"),
        "compared_dataset_count": compared,
        "issues": issues,
    }


def write_scientific_manifest(
    manifest: dict[str, Any],
    path: str | Path,
) -> Path:
    """Write a manifest or diff with deterministic JSON formatting."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return output


__all__ = [
    "SCHEMA",
    "SCHEMA_VERSION",
    "build_scientific_manifest",
    "compare_scientific_manifests",
    "write_scientific_manifest",
]
