#include "pdb_internal.hpp"

#include <algorithm>
#include <fstream>
#include <iomanip>
#include <map>
#include <stdexcept>

namespace xpongecpp {

void save_pdb(const Molecule& molecule, const std::filesystem::path& filename) {
    if (!molecule.validate()) {
        throw std::invalid_argument("cannot export invalid molecule");
    }
    std::vector<char> chain_ids(molecule.residues.size(), ' ');
    std::map<char, std::map<int, int>> chains;
    char alphabet = 'A';
    std::size_t start = 0;
    const auto residue_link_exists = [&](ResidueId left_id, ResidueId right_id) {
        const auto& left = molecule.residues[left_id];
        const auto& right = molecule.residues[right_id];
        if (!has_template(left.name) || !has_template(right.name)) {
            return false;
        }
        const auto& left_type = get_residue_template(left.name);
        const auto& right_type = get_residue_template(right.name);
        if (left_type.tail().empty() || right_type.head().empty()) {
            return false;
        }
        for (const auto& link : molecule.residue_links) {
            if (atom_pair_equals(molecule, link, left, left_type.tail(), right, right_type.head())) {
                return true;
            }
        }
        return false;
    };
    for (std::size_t i = 1; i <= molecule.residues.size(); ++i) {
        bool new_chain = i == molecule.residues.size();
        if (!new_chain) {
            new_chain = !residue_link_exists(static_cast<ResidueId>(i - 1), static_cast<ResidueId>(i));
        }
        if (new_chain) {
            const auto length = i - start;
            if (length > 1) {
                for (std::size_t j = 0; j < length; ++j) {
                    chain_ids[start + j] = alphabet;
                    chains[alphabet][static_cast<int>(j + 1)] = static_cast<int>(start + j + 1);
                }
                ++alphabet;
            }
            start = i;
        }
    }

    std::ofstream out(filename);
    if (!out) {
        throw std::runtime_error("failed to open PDB output: " + filename.string());
    }
    out << "REMARK   Generated By Xponge (Molecule)\n";
    out << std::fixed << std::setprecision(3);
    if (molecule.has_box) {
        out << "CRYST1" << std::setw(9) << molecule.box_length[0] << std::setw(9) << molecule.box_length[1]
            << std::setw(9) << molecule.box_length[2] << std::setw(7) << molecule.box_angle[0] << std::setw(7)
            << molecule.box_angle[1] << std::setw(7) << molecule.box_angle[2] << " P 1           1\n";
    }
    for (const auto& [chain_id, index_map] : chains) {
        std::vector<std::string> names;
        for (const auto& [pdb_index, residue_index_1] : index_map) {
            (void)pdb_index;
            names.push_back(normalized_residue_name(molecule.residues[residue_index_1 - 1].name));
        }
        for (std::size_t row = 0; row < names.size(); row += 13) {
            out << "SEQRES " << std::setw(3) << (row / 13 + 1) << " " << chain_id << std::setw(5)
                << names.size() << "  ";
            for (std::size_t i = row; i < std::min(row + 13, names.size()); ++i) {
                out << std::setw(3) << names[i] << (i + 1 == std::min(row + 13, names.size()) ? "" : " ");
            }
            out << "\n";
        }
    }

    std::vector<int> residue_pdb_indices(molecule.residues.size(), 1);
    std::unordered_map<char, int> next_index_by_chain;
    int next_blank_chain_index = 0;
    for (std::size_t i = 0; i < molecule.residues.size(); ++i) {
        if (chain_ids[i] == ' ') {
            residue_pdb_indices[i] = ++next_blank_chain_index;
        } else {
            residue_pdb_indices[i] = ++next_index_by_chain[chain_ids[i]];
        }
    }

    const auto pdb_output_element = [&](const Residue& residue, const Atom& atom) {
        if (!atom.element.empty()) {
            return atom.element;
        }
        if (has_template(residue.name)) {
            try {
                const auto& residue_type = get_residue_template(residue.name);
                const auto template_index = residue_type.atom_index(atom.name);
                const auto& template_atom = residue_type.atoms()[template_index];
                if (!template_atom.element.empty()) {
                    return template_atom.element;
                }
                if (template_atom.mass > 0.0) {
                    return guess_element_from_mass(template_atom.mass);
                }
            } catch (const std::exception&) {
            }
        }
        if (atom.mass > 0.0) {
            return guess_element_from_mass(atom.mass);
        }
        return guess_element(atom.name, "");
    };

    struct LinkRecord {
        char chain_a{' '};
        int resseq_a{0};
        char chain_b{' '};
        int resseq_b{0};
        std::string atom_a;
        std::string resname_a;
        std::string atom_b;
        std::string resname_b;
    };
    std::map<AtomId, std::vector<AtomId>> connects;
    std::vector<std::tuple<char, int, char, int>> ssbonds;
    std::vector<LinkRecord> links;
    const auto residue_atom_name = [&](const Residue& residue, AtomId atom_id) {
        if (atom_id < residue.atom_begin || atom_id >= residue.atom_begin + residue.atom_count) {
            return std::string{};
        }
        return molecule.atoms[atom_id].name;
    };
    const auto is_ssbond_atom = [&](const Residue& residue, AtomId atom_id) {
        if (!has_template(residue.name)) {
            return false;
        }
        const auto& type = get_residue_template(residue.name);
        const auto it = type.connect_atoms().find("ssbond");
        return it != type.connect_atoms().end() && residue_atom_name(residue, atom_id) == it->second;
    };
    for (const auto& link : molecule.residue_links) {
        AtomId atom_a = link.atom1;
        AtomId atom_b = link.atom2;
        if (atom_a > atom_b) {
            std::swap(atom_a, atom_b);
        }
        const auto res_a = molecule.atoms[atom_a].residue;
        const auto res_b = molecule.atoms[atom_b].residue;
        const char chain_a = chain_ids[res_a];
        const char chain_b = chain_ids[res_b];
        if (res_a + 1 == res_b && chain_a == chain_b && chain_a != ' ') {
            continue;
        }
        if (chain_a == ' ' || chain_b == ' ') {
            connects[atom_a].push_back(atom_b);
            connects[atom_b].push_back(atom_a);
            continue;
        }
        const auto& residue_a = molecule.residues[res_a];
        const auto& residue_b = molecule.residues[res_b];
        const std::string resname_a = normalized_residue_name(residue_a.name);
        const std::string resname_b = normalized_residue_name(residue_b.name);
        if (resname_a == "CYX" && resname_b == "CYX" && is_ssbond_atom(residue_a, atom_a) &&
            is_ssbond_atom(residue_b, atom_b)) {
            ssbonds.push_back({chain_a, residue_pdb_indices[res_a], chain_b, residue_pdb_indices[res_b]});
        } else {
            links.push_back({chain_a, residue_pdb_indices[res_a], chain_b, residue_pdb_indices[res_b],
                             residue_atom_name(residue_a, atom_a), resname_a,
                             residue_atom_name(residue_b, atom_b), resname_b});
        }
    }
    std::sort(ssbonds.begin(), ssbonds.end());
    for (std::size_t i = 0; i < ssbonds.size(); ++i) {
        const auto& [chain_a, resseq_a, chain_b, resseq_b] = ssbonds[i];
        out << "SSBOND " << std::setw(3) << (i + 1) << " CYX " << chain_a << pdb_int_field(4, resseq_a)
            << "    CYX " << chain_b << pdb_int_field(4, resseq_b) << "\n";
    }
    std::sort(links.begin(), links.end(), [](const LinkRecord& lhs, const LinkRecord& rhs) {
        return std::tie(lhs.chain_a, lhs.resseq_a, lhs.chain_b, lhs.resseq_b, lhs.atom_a, lhs.atom_b) <
               std::tie(rhs.chain_a, rhs.resseq_a, rhs.chain_b, rhs.resseq_b, rhs.atom_a, rhs.atom_b);
    });
    for (const auto& link : links) {
        out << "LINK        " << std::setw(4) << std::left << link.atom_a.substr(0, 4) << std::right << " "
            << std::setw(3) << link.resname_a << " " << link.chain_a << pdb_int_field(4, link.resseq_a)
            << "                " << std::setw(4) << std::left << link.atom_b.substr(0, 4) << std::right << " "
            << std::setw(3) << link.resname_b << " " << link.chain_b << pdb_int_field(4, link.resseq_b) << "\n";
    }

    std::size_t serial = 1;
    for (std::size_t residue_index = 0; residue_index < molecule.residues.size(); ++residue_index) {
        const auto& residue = molecule.residues[residue_index];
        const int resseq = residue_pdb_indices[residue_index];
        for (std::uint32_t local = 0; local < residue.atom_count; ++local) {
            const auto& atom = molecule.atoms[residue.atom_begin + local];
            const auto resname = normalized_residue_name(residue.name);
            out << (atom.record_name == "HETATM" ? "HETATM" : "ATOM  ") << pdb_int_field(5, static_cast<int>(serial))
                << " " << std::left << std::setw(4) << atom.name.substr(0, 4) << std::right << " " << std::setw(3)
                << resname << " " << chain_ids[residue_index] << pdb_int_field(4, resseq) << "    "
                << std::setw(8) << atom.x << std::setw(8) << atom.y << std::setw(8) << atom.z << std::setw(6)
                << std::setprecision(2) << atom.occupancy << std::setw(6) << atom.temp_factor << std::setprecision(3)
                << "          " << std::setw(2) << pdb_output_element(residue, atom).substr(0, 2) << "\n";
            ++serial;
        }
        const bool is_last = residue_index + 1 == molecule.residues.size();
        if (is_last || chain_ids[residue_index + 1] != chain_ids[residue_index] || chain_ids[residue_index] == ' ') {
            out << "TER\n";
        }
    }

    for (auto& [atom, atoms] : connects) {
        std::sort(atoms.begin(), atoms.end());
        for (std::size_t i = 0; i < atoms.size(); i += 4) {
            out << "CONECT" << pdb_int_field(5, static_cast<int>(atom + 1));
            for (std::size_t j = i; j < std::min(i + 4, atoms.size()); ++j) {
                out << pdb_int_field(5, static_cast<int>(atoms[j] + 1));
            }
            out << "\n";
        }
    }
    out << "END\n";
}

}  // namespace xpongecpp
